apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-coroot
  namespace: coroot
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    #- ReadWriteMany
  nfs:
    path: /data/k8s/coroot
    server: 192.168.8.211
